config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'restaurants#index'
  resources :restaurants
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, :address, :category, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :rating, :content, presence: true
  validates :rating, numericality: { only_integer: true }, inclusion: { in: 0..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[show edit]

  def index
    @restaurants = Restaurant.all
  end

  def show; end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    redirect_to restaurant_path(@restaurant)
  end

  def edit; end

  def update; end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BestEAT's</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <div class="container mt-3">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">BestEAT's</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Add Restaurant</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Edit Restaurant</a>
          </li>
        </ul>
      </div>
    </nav>
      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/edit.html.erb
<h1>Edit Restaurant</h1>

<%= render simple_form(@restaurant) %>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<%= link_to 'Add Restaurant', new_restaurant_path, class: "btn btn-success mb-2" %>

<div class="list-group col-8">
  <% @restaurants.each do |restaurant| %>
    <div class="list-group-item list-group-item-action flex-column align-items-start mb-2 border">

      <%= link_to restaurant_path(restaurant) do %>
      <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">
              <%= restaurant.name  %>
            </h5>
            <small>
              <%= restaurant.category %>
            </small>
          </div>
          <p><%= restaurant.phone_number %></p>
          <p><%= restaurant.address %></p>
      <% end %>
    </div>
  <% end %>
</div>

app/views/restaurants/new.html.erb
<h1>Add a Restaurant</h1>


<%= simple_form_for(@restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category %>
  <%= f.submit class: "btn btn-success" %>
<% end %>

app/views/restaurants/show.html.erb
<%= link_to 'Back to Restaurants', restaurants_path %>

<h1><%= @restaurant.name %></h1>

<p><%= @restaurant.category %></p>
<p><%= @restaurant.phone_number %></p>
<p><%= @restaurant.address %></p>

<hr>

<%= link_to 'Edit Restaurant', edit_restaurant_path %>
<%= link_to 'Remove Restaurant',
    restaurant_path(@restaurant),
    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>